apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
  - name: container-name
    image: minio/mc
    command: ["/bin/sh"]
    args: ["-c", "container-command"]
  restartPolicy: Never
