local:
  cpus: 8
  memory: 16192
  storage: 40g
  gpu_support: true
  use_overlay: false
  #provider: minikube
  provider: mikrok8s
  #vm_driver: virtualbox
  vm_driver: kvm2

remote:
  type: aws
  cluster_name: data-mill
  bucket_name: data-mill
  region: "us-east1"
  zones: "us-east1a"
  no_nodes: 2
  node_size=t2.medium
