jhub:
  release: jhub
  version: 0.8-de79a04
  config_file: jhub_config.yaml
  setup_timeout: 7200

#  ds_image:
#    use_local_image: true
#    name: data-mill/python_env
#    tag: 0.1.1

#  ds_image:
#    use_local_image: true
#    name: data-mill/python_env
#    tag: 0.1

#  ds_image:
#    use_local_image: false
#    name: jupyter/scipy-notebook
#    tag: latest
