hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']
    c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    c.KubeSpawner.profile_list = [
      {
        'display_name': 'Default python_env environment',
        'description': 'An extension of the scipy-notebook with S3, Dask distributed, Spark and few more basic libraries',
        'default': True,
        'kubespawner_override': {
            'image': 'data-mill/python_env:0.1',
            'cpu_limit': 1,
            'mem_limit': '1G',
        }
      }, {
        'display_name': 'Community jupyter/scipy-notebook:latest',
        'description': 'A fully fledged scientific python environment from the jupyter community',
        'kubespawner_override': {
            'image': 'jupyter/scipy-notebook:latest',
            'cpu_limit': 1,
            'mem_limit': '1G',
        }
      },{
        'display_name': 'Community jupyter/pyspark-notebook:latest',
        'description': 'A fully fledged scientific python environment from the jupyter community',
        'kubespawner_override': {
            'image': 'jupyter/pyspark-notebook:latest',
            'cpu_limit': 1,
            'mem_limit': '1G',
        }
      },{
        'display_name': 'Community jupyter/tensorflow-notebook:latest',
        'description': 'A fully fledged scientific python environment from the jupyter community',
        'kubespawner_override': {
            'image': 'jupyter/tensorflow-notebook:latest',
            'cpu_limit': 1,
            'mem_limit': '1G',
        }
      }
    ]

singleuser:
  defaultUrl: "/lab"
  #image:
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    # More images at: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
    # Example processing from the notebook: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#apache-spark
    #name: jupyter/pyspark-notebook
    #name: jupyter/scipy-notebook
    #tag: latest
  # please check: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner

prePuller:
  hook:
    enabled: true
  continuous:
    enabled: true
  extraImages:
    pythonds:
      name: jupyter/scipy-notebook
      tag: latest
      policy: IfNotPresent
    pyspark:
      name: jupyter/pyspark-notebook
      tag: latest
      policy: IfNotPresent
    pytensor:
      name: jupyter/tensorflow-notebook
      tag: latest
      policy: IfNotPresent

scheduling:
  userScheduler:
    enabled: true

debug:
  enabled: true

# authentication aspects
# https://z2jh.jupyter.org/en/stable/authentication.html

auth:
  admin:
    access: false
