hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']
    c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
    c.KubeSpawner.profile_list = [
      {
        'display_name': 'Enhanced scipy environment (datamillcloud/python_env:latest)',
        'description': 'An extension of the scipy-notebook with S3, Dask distributed and a few more client libraries',
        'default': True,
        'kubespawner_override': {
            'singleuser_image_spec': 'datamillcloud/python_env:latest',
            'cpu_limit': 1,
            'mem_limit': '1G',
        }
      },
      {
        'display_name': 'Enhanced pyspark-notebook environment (datamillcloud/pyspark_env:latest)',
        'description': 'An extension of the pyspark-notebook with S3, Dask distributed and a few more client libraries',
        'kubespawner_override': {
            'singleuser_image_spec': 'datamillcloud/pyspark_env:latest',
            'cpu_limit': 1,
            'mem_limit': '1G',
        }
      },
      {
        'display_name': 'Enhanced tensorflow-notebook environment (datamillcloud/pydl_env:latest)',
        'description': 'An extension of the tensorflow-notebook with S3, Dask distributed and few more client libraries',
        'kubespawner_override': {
            'singleuser_image_spec': 'datamillcloud/pydl_env:latest',
            'cpu_limit': 1,
            'mem_limit': '1G',
        }
      }
    ]


singleuser:
  defaultUrl: "/lab"
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    # More images at: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
    # please check: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner

prePuller:
  hook:
    enabled: true
  continuous:
    enabled: true
  extraImages:
    pythonds:
      name: datamillcloud/python_env
      tag: latest
      policy: IfNotPresent
    pyspark:
      name: datamillcloud/pyspark_env
      tag: latest
      policy: IfNotPresent
    pytensor:
      name: datamillcloud/pydl_env
      tag: latest
      policy: IfNotPresent

scheduling:
  userScheduler:
    enabled: true

debug:
  enabled: true

# authentication aspects
# https://z2jh.jupyter.org/en/stable/authentication.html

auth:
  admin:
    access: false
proxy:
  service:
    type: ClusterIP
